name: Google Indexing API
on:
  push:
    branches:
      - main
    paths:
      - '**/*.html'

jobs:
  notify-google:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed to get the list of modified files

      - name: Get modified HTML files
        id: files
        run: |
          git diff --name-only HEAD^ HEAD > modified_files.txt
          cat modified_files.txt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Googleapis
        run: npm install googleapis

      - name: Run Google Indexing Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_INDEXING_CREDENTIALS }}
        run: node .github/scripts/google-index.js
